Repository assistify/Rocket.Chat, pull requests merged in 2018-06, with the labels that each got.

#340 added publish on docker step for circle ci
  .circleci/config.yml
Labels: Priority: High, Type: Improvement, progress:working

#342 fixed intial statistic creation
  packages/rocketchat-statistics/server/functions/getUsages.js
Labels: Priority: Critical, Type: Bug, progress:working

#344 Building Dockerimage on circle ci
  .circleci/config.yml
  .docker/Dockerfile.local
Labels: Priority: High, Type: Bug, progress:working

#348 remove $loki from room propagated to the integration
  packages/rocketchat-integrations/server/lib/triggerHandler.js
Labels: progress:working

#346 [FIX] #345 - where smarti conversation cache got out of synch
  packages/assistify-ai/config.js
  packages/assistify-ai/server/SmartiProxy.js
  packages/assistify-ai/server/SmartiRouter.js
  packages/assistify-ai/server/hooks/sendMessageToKnowledgeAdapter.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-ai/server/methods/SmartiReload.js
  packages/assistify-ai/server/methods/SmartiWidgetBackend.js
  packages/assistify-help-request/package.js
  packages/assistify-help-request/server/hooks/sendMessageToKnowledgeAdapter.js
  packages/assistify-help-request/server/methods/createExpertise.js
  packages/assistify-help-request/server/methods/createRequestFromExpertise.js
  packages/assistify-help-request/server/methods/createRequestFromRoomId.js
  packages/assistify-help-request/server/models/LivechatExternalMessage.js
  packages/rocketchat-i18n/i18n/assistifyAI.de.i18n.yml
  packages/rocketchat-i18n/i18n/assistifyAI.en.i18n.yml
  tests/end-to-end/assistify/02-create-request.js
  tests/end-to-end/assistify/03-global-announcement.js
  tests/end-to-end/assistify/04-settings-based-permissions.js
  tests/end-to-end/assistify/10-autotranslate.js
  tests/end-to-end/ui_smarti/03-resync-smarti.js
  tests/pageobjects/assistify.page.js
  tests/pageobjects/side-nav.page.js
Labels: progress:working

#355 Remove caching of sychronization status
  packages/assistify-ai/client/views/app/tabbar/smarti.html
  packages/assistify-ai/client/views/app/tabbar/smarti.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-ai/server/methods/SmartiReload.js
Labels: progress:working

#357 [WIP] Feature/optimize sync
  packages/assistify-ai/server/lib/SmartiAdapter.js
Labels: progress:working

#358 prevent delta sync
  packages/assistify-ai/server/lib/SmartiAdapter.js
Labels: progress:working

#361 use asynchronous call back in smarti widget backend
  packages/assistify-ai/server/methods/SmartiWidgetBackend.js
Labels: progress:working

#365 Release 0.63.3 0.8.2
  HISTORY.md
  packages/rocketchat-integrations/server/lib/triggerHandler.js
  packages/rocketchat-lib/rocketchat.info
Labels: progress:working

#370 #369 - Use synchronous analysis when initializing the Smarti widget
  packages/assistify-ai/server/methods/SmartiWidgetBackend.js
Labels: progress:working
