Repository assistify/Rocket.Chat, pull requests merged in 2018-03, with the labels that each got.

#265 Fix Smarti-Adapter for livechats
  packages/assistify-ai/server/lib/SmartiAdapter.js
Labels: progress:working

#275 Enable guest user to create requests
  packages/rocketchat-ui-sidenav/client/toolbar.js
  packages/rocketchat-ui/client/views/app/createRooms.js
Labels: Type: Bug, progress:working

#277 added pin-message permission to user default permissions
  packages/rocketchat-authorization/server/startup.js
Labels: RC downport-candidate, Type: Bug, progress:working

#267 Feature/#145 ask question from room
  .travis.yml
  package-lock.json
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-help-request/client/public/icons.svg
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateExpertise.js
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateRequest.js
  packages/assistify-help-request/client/views/messageActions/AssistifyMessageAction.js
  packages/assistify-help-request/lib/messageTypes/requestClosed.js
  packages/assistify-help-request/lib/messageTypes/threadMessage.js
  packages/assistify-help-request/package.js
  packages/assistify-help-request/server/api.js
  packages/assistify-help-request/server/methods/createRequest.js
  packages/assistify-help-request/server/methods/createRequestBase.js
  packages/assistify-help-request/server/methods/createRequestFactory.js
  packages/assistify-help-request/server/methods/createRequestFromExpertise.js
  packages/assistify-help-request/server/methods/createRequestFromRoomId.js
  packages/assistify-help-request/server/models/Message.js
  packages/assistify-help-request/startup/rolesAndPermissions.js
  packages/rocketchat-i18n/i18n/assistifyHelpRequest.de.i18n.yml
  packages/rocketchat-i18n/i18n/assistifyHelpRequest.en.i18n.yml
  packages/rocketchat-lib/client/views/SimpleRoomCreateDialog.js
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-message-attachments/client/fieldTypeThreadReference.html
  packages/rocketchat-message-attachments/client/fieldTypeThreadReference.js
  packages/rocketchat-message-attachments/client/messageAttachment.html
  packages/rocketchat-message-attachments/client/renderField.html
  packages/rocketchat-message-attachments/client/renderField.js
  packages/rocketchat-message-attachments/client/stylesheets/messageAttachments.css
  packages/rocketchat-message-attachments/package.js
  packages/rocketchat-statistics/server/functions/getUsages.js
  tests/end-to-end/assistify/02-create-request.js
  tests/pageobjects/assistify.page.js
  tests/pageobjects/global.js
  tests/pageobjects/main-content.page.js
Labels: progress:working

#281 Assistify circle ci
  .circleci/config.yml
  .scripts/check-deploy.sh
  .scripts/continueTesting.sh
  .scripts/deploy-assistify-chat.sh
  .scripts/dockerfile-smarti-with-nlp
  .scripts/seperateTesting.sh
  .scripts/smarti.sh
  .scripts/start.js
  .travis.yml
Labels: progress:working

#282 Rename-safe navigation in threads
  packages/assistify-help-request/server/methods/createRequestBase.js
  packages/assistify-help-request/server/methods/createRequestFromRoomId.js
  packages/rocketchat-lib/lib/routes.js
  packages/rocketchat-lib/package.js
  packages/rocketchat-lib/server/methods/getCurrentMessageRouteLink.js
  packages/rocketchat-lib/server/models/Messages.js
  packages/rocketchat-livechat/.app/package-lock.json
Labels: progress:working

#294 Hotfix/#292 adapt assistify toolbar
  packages/assistify-help-request/client/views/tabbar/tabbarConfig.js
Labels: progress:working

#276 member of a request can invite other users
  packages/rocketchat-authorization/server/startup.js
Labels: progress:working

#296 Open Smarti-Tab in requests and livechats
  packages/assistify-help-request/client/hooks/openAiTab.js
Labels: progress:working

#185 Enable multiline question while create new request
  packages/assistify-help-request/assets/stylesheets/helpRequest.less
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateRequest.html
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateRequest.js
  packages/assistify-help-request/config.js
  packages/assistify-help-request/package.js
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-ui/client/lib/textarea-autogrow.js
Labels: progress:working

#244 Room Name upper case is not supported.
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateExpertise.js
  packages/assistify-help-request/lib/roomTypes/expertise.js
  packages/assistify-help-request/lib/roomTypes/request.js
  packages/rocketchat-channel-settings/client/views/channelSettings.js
Labels: progress:working

#298 Hotfix for statistics
  packages/rocketchat-statistics/server/functions/getUsages.js
Labels: Type: Bug, progress:working

#300 Revert "Enable multiline question while create new request"
  packages/assistify-help-request/assets/stylesheets/helpRequestContext.less
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateRequest.html
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateRequest.js
  packages/assistify-help-request/config.js
  packages/assistify-help-request/package.js
  packages/rocketchat-livechat/.app/package-lock.json
  packages/rocketchat-ui/client/lib/textarea-autogrow.js
Labels: progress:working
