Repository assistify/Rocket.Chat, pull requests merged in 2018-02, with the labels that each got.

#215 #211 - Adjust config-expert permissions
  packages/assistify-defaults/server/roles.js
Labels: progress:working

#216 #211 - Removed misplaced settings from permission section
  packages/assistify-defaults/server/roles.js
Labels: progress:working

#219 #211 - Removed auto role assignment for auth service registration, si…
  packages/assistify-defaults/server/roles.js
Labels: progress:working

#223 FIX #211
  packages/assistify-defaults/server/roles.js
Labels: progress:working

#224 Fixing #208 - wrong label in account settings
  packages/rocketchat-i18n/i18n/de-AT.i18n.json
  packages/rocketchat-i18n/i18n/de.i18n.json
Labels: progress:working

#200 New smarti widget
  .meteor/versions
  packages/assistify-ai/client/public/assistify.png
  packages/assistify-ai/client/public/bulb.png
  packages/assistify-ai/client/public/stylesheets/smarti.css
  packages/assistify-ai/client/views/app/tabbar/smarti.html
  packages/assistify-ai/client/views/app/tabbar/smarti.js
  packages/assistify-ai/package.js
  packages/assistify-ai/server/SmartiProxy.js
  packages/assistify-ai/server/hooks/sendMessageToKnowledgeAdapter.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-ai/server/methods/SmartiWidgetBackend.js
  packages/assistify-help-request/server/hooks/sendMessageToKnowledgeAdapter.js
  packages/rocketchat-livechat/.app/package-lock.json
  tests/end-to-end/ui_smarti/00-preparation.js
  tests/end-to-end/ui_smarti/01-integration.js
  tests/end-to-end/ui_smarti/02-widget.js
  tests/end-to-end/ui_smarti/05-cleanup.js
  tests/pageobjects/assistify.page.js
Labels: progress:working

#233 Provide more information for outgoing integrations
  packages/rocketchat-integrations/server/lib/triggerHandler.js
Labels: progress:working

#225 Show custom room types icon in channel header
  packages/rocketchat-ui/client/components/header/header.js
Labels: progress:working

#237 fix all linting errors plus 2 bug fixes in tests
  .scripts/dockerfile
  .scripts/seperateTesting.sh
  .scripts/smarti.sh
  packages/assistify-ai/server/hooks/sendMessageToKnowledgeAdapter.js
  packages/assistify-ai/server/lib/AiApiAdapter.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateExpertise.js
  packages/assistify-help-request/client/views/creationDialog/AssistifyCreateRequest.js
  packages/assistify-help-request/client/views/sideNav/listRequestsFlex.js
  packages/assistify-help-request/server/methods/requestsList.js
  packages/assistify-help-request/server/models/LivechatExternalMessage.js
  packages/assistify-help-request/server/models/Rooms.js
  packages/assistify-help-request/server/models/Users.js
  packages/meteor-accounts-saml/saml_utils.js
  packages/rocketchat-custom-oauth/server/custom_oauth_server.js
  packages/rocketchat-lib/client/views/SimpleRoomCreateDialog.js
  packages/rocketchat-lib/server/functions/saveUser.js
  packages/rocketchat-lib/server/functions/settings.js
  packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
  packages/rocketchat-lib/server/models/Rooms.js
  packages/rocketchat-slackbridge/server/slackbridge.js
  server/publications/room.js
  tests/end-to-end/api/06-outgoing-integrations.js
  tests/end-to-end/api/11-custom-roomtypes.js
  tests/end-to-end/ui/14-global-announcement.js
  tests/end-to-end/ui/15-settings-based-permissions.js
  tests/end-to-end/ui_smarti/00-preparation.js
  tests/end-to-end/ui_smarti/01-integration.js
  tests/end-to-end/ui_smarti/02-widget.js
  tests/end-to-end/ui_smarti/05-cleanup.js
  tests/pageobjects/assistify.page.js
Labels: Type: Bug, Type: Enhancement, Type: Improvement, progress:working

#229 Run tests separately
  .scripts/seperateTesting.sh
  .travis.yml
Labels: Type: Test, progress:working

#240 added verbose log to rc build
  .scripts/dockerfile
  .scripts/smarti.sh
  .scripts/start.js
  .travis.yml
Labels: progress:working

#243 temporary disable second test run without oplog mongodb
  .travis.yml
Labels: progress:working

#247 #246 - When picking users in the create channel dialog, the select bo…
  packages/rocketchat-theme/client/imports/components/modal/create-channel.css
Labels: progress:working

#253 add a script to continue testing from the point where it crashed
  .scripts/continueTesting.sh
Labels: Type: Enhancement, Type: Test

#257 Travis full pipeline
  .scripts/check-deploy.sh
  .travis.yml
Labels: progress:working

#260 stored secrets in travis.yml
  .travis.yml
Labels: progress:working
