Repository assistify/Rocket.Chat, pull requests merged in 2018-09, with the labels that each got.

#431 Provide detailed anonymized usage-statistics
  packages/rocketchat-statistics/package.js
  packages/rocketchat-statistics/server/functions/get.js
  packages/rocketchat-statistics/server/functions/getUsages.js
Labels: progress:working

#432 Smarti in plain Rocket.Chat
  .circleci/config.yml
  .meteor/packages
  .meteor/versions
  package-lock.json
  packages/assistify-ai/README.md
  packages/assistify-ai/assistify-ai.js
  packages/assistify-ai/client/chatpalAdoption.js
  packages/assistify-ai/client/hooks/openAiTab.js
  packages/assistify-ai/client/public/assistify-beta.png
  packages/assistify-ai/client/public/assistify.png
  packages/assistify-ai/client/public/bulb.png
  packages/assistify-ai/client/public/icons.svg
  packages/assistify-ai/client/public/stylesheets/smarti.css
  packages/assistify-ai/client/smartiLoader.js
  packages/assistify-ai/client/tabbar.js
  packages/assistify-ai/client/views/app/tabbar/smarti.html
  packages/assistify-ai/client/views/app/tabbar/smarti.js
  packages/assistify-ai/config.js
  packages/assistify-ai/models/AssistifySmarti.js
  packages/assistify-ai/package.js
  packages/assistify-ai/server/SmartiProxy.js
  packages/assistify-ai/server/SmartiRouter.js
  packages/assistify-ai/server/hooks/closeLivechatKnowledgeAdapter.js
  packages/assistify-ai/server/hooks/sendMessageToKnowledgeAdapter.js
  packages/assistify-ai/server/inject.js
  packages/assistify-ai/server/lib/AiApiAdapter.js
  packages/assistify-ai/server/lib/KnowledgeAdapterProvider.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-ai/server/methods/SmartiReload.js
  packages/assistify-ai/server/methods/SmartiWidgetBackend.js
  packages/assistify-ai/server/migrations.js
  packages/rocketchat-i18n/i18n/assistifyAI.de.i18n.json
  packages/rocketchat-i18n/i18n/assistifyAI.en.i18n.json
  tests/end-to-end/ui_smarti/00-preparation.js
  tests/end-to-end/ui_smarti/01-integration.js
  tests/end-to-end/ui_smarti/02-widget.js
  tests/end-to-end/ui_smarti/03-resync-smarti.js
  tests/end-to-end/ui_smarti/05-cleanup.js
  tests/end-to-end/ui_smarti/README.md
  tests/pageobjects/assistify.page.js
Labels: progress:working

#429 Port: Setting based permissions
  .circleci/config.yml
  package-lock.json
  packages/rocketchat-authorization/client/startup.js
  packages/rocketchat-authorization/client/stylesheets/permissions.css
  packages/rocketchat-authorization/client/views/permissions.html
  packages/rocketchat-authorization/client/views/permissions.js
  packages/rocketchat-authorization/lib/rocketchat.js
  packages/rocketchat-authorization/server/methods/addPermissionToRole.js
  packages/rocketchat-authorization/server/methods/removeRoleFromPermission.js
  packages/rocketchat-authorization/server/publications/permissions.js
  packages/rocketchat-authorization/server/startup.js
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
  packages/rocketchat-lib/server/methods/saveSetting.js
  packages/rocketchat-lib/server/publications/settings.js
  packages/rocketchat-livechat/app/package-lock.json
  packages/rocketchat-ui-admin/client/SettingsCachedCollection.js
  packages/rocketchat-ui-admin/client/admin.html
  packages/rocketchat-ui-admin/client/admin.js
  packages/rocketchat-ui-admin/client/adminFlex.html
  packages/rocketchat-ui-admin/client/adminFlex.js
  packages/rocketchat-ui-sidenav/client/sidebarHeader.js
  tests/end-to-end/ui/13a-setting-permissions.js
  tests/pageobjects/administration.page.js
Labels: progress:working

#430 Provide default Assistify-specific configuration of Rocket.Chat
  .meteor/packages
  .meteor/versions
  packages/assistify-configuration/README.md
  packages/assistify-configuration/package.js
  packages/assistify-configuration/server/config.js
  packages/assistify-configuration/server/roles.js
Labels: progress:working

#462 Add an optional explicit callback URL for Smarti
  packages/assistify-ai/config.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/rocketchat-i18n/i18n/assistifyAI.de.i18n.json
  packages/rocketchat-i18n/i18n/assistifyAI.en.i18n.json
Labels: progress:working

#465 Grant more timeforsetting permissions to appear
  tests/end-to-end/ui/13a-setting-permissions.js
Labels: progress:working

#467 add threads as new room type t to statistic
  packages/rocketchat-statistics/server/functions/getUsages.js
Labels: progress:working

#463 Resync batches of messages
  packages/assistify-ai/config.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/rocketchat-i18n/i18n/assistifyAI.de.i18n.json
  packages/rocketchat-i18n/i18n/assistifyAI.en.i18n.json
  packages/rocketchat-ui-sidenav/client/sideNav.html
Labels: progress:working

#487 fix create label
  packages/assistify-threading/client/views/creationDialog/CreateThread.html
Labels: progress:working

#492 #490 - using correct label
  packages/assistify-ai/config.js
Labels: progress:working

#493 Speed up member find for threads
  packages/assistify-threading/server/methods/createThread.js
Labels: Type: Improvement, progress:working

#491 Fix navigation to channels using mention links
  client/routes/roomRoute.js
  packages/rocketchat-ui/client/views/app/room.js
Labels: progress:working

#500 fix user undefined in isMessageRelevant
  packages/assistify-ai/server/hooks/sendMessageToKnowledgeAdapter.js
Labels: Type: Bug, progress:working

#498 fix layout for leave, hide room
  packages/rocketchat-channel-settings/client/views/channelSettings.html
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: Cmp: Rocket.Chat Core, Type: Bug, progress:working

#495 removed unused setting properties
  packages/assistify-configuration/server/config.js
Labels: progress:working

#503 [Livechat] Notify agents when a new chat is queued
  packages/rocketchat-lib/server/lib/index.js
  packages/rocketchat-lib/server/lib/sendNotificationsOnMessage.js
  packages/rocketchat-livechat/.app/i18n/de.i18n.json
  packages/rocketchat-livechat/.app/i18n/en.i18n.json
  packages/rocketchat-livechat/server/lib/QueueMethods.js
Labels: progress:working

#508 Hide system messages in threads
  packages/assistify-threading/server/methods/createThread.js
Labels: Type: Improvement, progress:working

#519 [Livechat] Fix agent joining on pick from guestpool
  packages/rocketchat-livechat/.app/client/lib/_livechat.js
Labels: progress:working

#521 SAML-registration: get rid of null-names
  packages/assistify-migrations/server/startup/migrations.js
  packages/meteor-accounts-saml/saml_server.js
Labels: progress:working

#523 Release 0.68.5 0.9.1
  HISTORY.md
  packages/assistify-threading/server/methods/createThread.js
  packages/rocketchat-lib/rocketchat.info
  packages/rocketchat-livechat/.app/client/lib/_livechat.js
Labels: progress:working

#520 [Threading] Configure limit of max invited users
  packages/assistify-threading/config.js
  packages/assistify-threading/server/methods/createThread.js
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: progress:working

#509 Create error toast when parent room invalid
  packages/assistify-threading/client/views/creationDialog/CreateThread.js
  packages/assistify-threading/client/views/creationDialog/CreateThreadInputError.html
Labels: Priority: High, Type: Bug, progress:working

#531 Remove the v in the semver version - fixes #530
  packages/rocketchat-lib/rocketchat.info
Labels: progress:working

#534 Create threading-messages despite no-sys-messages
  packages/assistify-threading/server/methods/createThread.js
Labels: progress:working

#527 Allow user with "bulk-register-user" permission to send invitation mails
  packages/rocketchat-lib/server/methods/sendInvitationEmail.js
  packages/rocketchat-ui-admin/client/users/adminInviteUser.html
  packages/rocketchat-ui-admin/client/users/adminInviteUser.js
Labels: progress:working

#506 Also identify private channels for mention links
  client/routes/roomRoute.js
  packages/rocketchat-mentions/Mentions.js
  packages/rocketchat-mentions/server/server.js
  packages/rocketchat-mentions/tests/client.tests.js
  packages/rocketchat-ui/client/views/app/room.js
  server/methods/getRoomNameAndTypeById.js
Labels: progress:working

#536 Scripts for dedicated integrtion test execution
  .scripts/separateTesting.sh
  package.json
  tests/end-to-end/api/06-outgoing-integrations.js
  tests/end-to-end/ui/09-channel.js
  tests/end-to-end/ui/10-user-preferences.js
  tests/end-to-end/ui/11-admin.js
  tests/end-to-end/ui/14-message-popup.js
  tests/pageobjects/side-nav.page.js
Labels: progress:working

#533 Translation services
  .docker/Dockerfile.local
  .dockerignore
  package-lock.json
  packages/assistify-dbs-translation/.npm/package/.gitignore
  packages/assistify-dbs-translation/.npm/package/README
  packages/assistify-dbs-translation/.npm/package/npm-shrinkwrap.json
  packages/rocketchat-autotranslate/.npm/package/.gitignore
  packages/rocketchat-autotranslate/.npm/package/README
  packages/rocketchat-autotranslate/.npm/package/npm-shrinkwrap.json
  packages/rocketchat-autotranslate/client/lib/actionButton.js
  packages/rocketchat-autotranslate/client/lib/autotranslate.js
  packages/rocketchat-autotranslate/client/views/autoTranslateFlexTab.js
  packages/rocketchat-autotranslate/package.js
  packages/rocketchat-autotranslate/server/autotranslate.js
  packages/rocketchat-autotranslate/server/dbsTranslate.js
  packages/rocketchat-autotranslate/server/deeplTranslate.js
  packages/rocketchat-autotranslate/server/googleTranslate.js
  packages/rocketchat-autotranslate/server/index.js
  packages/rocketchat-autotranslate/server/models/Settings.js
  packages/rocketchat-autotranslate/server/settings.js
  packages/rocketchat-i18n/i18n/de.i18n.json
  packages/rocketchat-i18n/i18n/en.i18n.json
Labels: progress:working

#538 [Fix]Exclude DBS package from core RC and change error message.
  packages/assistify-dbs-translation/.npm/package/.gitignore
  packages/assistify-dbs-translation/.npm/package/README
  packages/assistify-dbs-translation/.npm/package/npm-shrinkwrap.json
  packages/rocketchat-autotranslate/server/dbsTranslate.js
Labels: progress:working

#529 SmartiProxy: Use params option instead building HTTP query strings
  packages/assistify-ai/server/SmartiProxy.js
  packages/assistify-ai/server/lib/SmartiAdapter.js
  packages/assistify-ai/server/methods/SmartiWidgetBackend.js
Labels: Type: Improvement, progress:working
